[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"  # or "out" if using next export

[context.production]
  command = "npm install --legacy-peer-deps && npm run build"
